const { randomUUID } = require('crypto'); const Transaction = require('../models/Transaction'); const { ApiError } = require('../utils/helpers'); const verificationService = require('./verificationService'); const turnkeyService = require('./turnkeyService');
async function prepareTransaction({ userId, walletId, recipient, amount, network, memo }) {
  const transaction = await Transaction.create({ userId, transactionId: randomUUID(), walletId, recipient, amount, network, memo });
  try { const challenge = await verificationService.startChallenge({ transaction }); return { transaction, challenge }; }
  catch (error) { await Transaction.findByIdAndDelete(transaction._id); throw error; }
}
async function listTransactions({ userId, page = 1, limit = 20 }) { const safeLimit = Math.min(Math.max(Number(limit) || 20, 1), 100); const safePage = Math.max(Number(page) || 1, 1); const [transactions, total] = await Promise.all([Transaction.find({ userId }).sort({ createdAt: -1 }).skip((safePage - 1) * safeLimit).limit(safeLimit), Transaction.countDocuments({ userId })]); return { transactions, pagination: { page: safePage, limit: safeLimit, total } }; }
async function getTransaction({ userId, transactionId }) { const transaction = await Transaction.findOne({ _id: transactionId, userId }); if (!transaction) throw new ApiError(404, 'Transaction not found.'); return transaction; }
async function finalizeTransaction({ userId, transactionId, verificationPayload }) { const transaction = await getTransaction({ userId, transactionId }); if (transaction.status !== 'pending') throw new ApiError(409, 'Transaction is not awaiting verification.'); const verification = await verificationService.verifyChallenge({ transaction, ...verificationPayload }); if (!verification?.verificationToken) throw new ApiError(403, 'Visual Password verification was not accepted.'); const submitted = await turnkeyService.signAndSubmitTransaction({ ...transaction.toObject(), verificationToken: verification.verificationToken }); transaction.status = 'submitted'; transaction.txHash = submitted.txHash; transaction.verificationToken = verification.verificationToken; await transaction.save(); return transaction; }
module.exports = { prepareTransaction, listTransactions, getTransaction, finalizeTransaction };
