'use client';

import { useMemo, useState } from 'react';
import { Coins, Info } from 'lucide-react';
import Button from '../ui/Button';

/**
 * Computes the mock amount-verification code:
 *   first digit  = first digit of the amount
 *   second digit = number of digits in the amount
 *
 * e.g. 500000 -> "5" + "6" digits -> "56"; 2500 -> "24"; 950 -> "93".
 * Non-digit characters (decimal points, symbols) are stripped first
 * so this still produces a sensible code for amounts like "5.247".
 */
function computeAmountCode(amount) {
  const digitsOnly = String(amount ?? '').replace(/[^0-9]/g, '') || '0';
  const firstDigit = digitsOnly[0];
  const digitCount = String(digitsOnly.length);
  return `${firstDigit}${digitCount}`;
}

/**
 * Stage 2 of transaction verification: confirms the user recognizes
 * the exact amount being sent by echoing back a short code derived
 * from it.
 *
 * The algorithm is mocked/computed entirely on the frontend for this
 * pass -- in production the code would be generated by the backend
 * for this specific transaction (see services/verificationService.js
 * -> startVerification()) and never derived client-side.
 *
 * @param {string} amount
 * @param {string} symbol
 */
export default function AmountVerification({ amount = '5', symbol = 'ETH', onContinue, onBack }) {
  const verificationCode = useMemo(() => computeAmountCode(amount), [amount]);
  const [input, setInput] = useState('');
  const isCorrect = input === verificationCode;

  return (
    <div className="vp-theme flex flex-col gap-6">
      <div>
        <div className="flex items-center gap-2 text-sm font-semibold text-[var(--vp-primary-hover)]">
          <Coins className="h-4 w-4" aria-hidden="true" />
          Amount Verification
        </div>
        <p className="mt-2 text-base text-[var(--vp-text-secondary)]">
          Confirm the code shown below to verify you recognize this amount.
        </p>
      </div>

      <div className="vp-card px-6 py-6 text-center">
        <p className="text-sm text-[var(--vp-text-secondary)]">Transaction Amount</p>
        <p className="mt-1.5 font-mono-data text-3xl font-semibold text-[var(--vp-text-primary)]">
          {amount} {symbol}
        </p>
        <div className="mt-5 border-t border-[var(--vp-border)] pt-5">
          <p className="text-sm text-[var(--vp-text-secondary)]">Verification Code</p>
          <p className="mt-1.5 font-mono-data text-4xl font-bold tracking-[0.3em] text-[var(--vp-primary)]">
            {verificationCode}
          </p>
        </div>
      </div>

      <div className="flex gap-2.5 rounded-2xl border border-[var(--vp-border)] bg-[#fff9f0] px-4 py-3.5">
        <Info className="h-4 w-4 shrink-0 text-[var(--vp-secondary)] mt-0.5" aria-hidden="true" />
        <p className="text-sm leading-relaxed text-[var(--vp-text-secondary)]">
          The first digit comes from the first digit of the amount. The second digit comes from
          the number of digits in the amount.
        </p>
      </div>

      <div>
        <label htmlFor="amount-code" className="mb-1.5 block text-sm font-semibold text-[var(--vp-text-primary)]">
          Enter the code above
        </label>
        <input
          id="amount-code"
          type="text"
          inputMode="numeric"
          maxLength={verificationCode.length}
          value={input}
          onChange={(event) => setInput(event.target.value)}
          className="vp-input font-mono-data text-center text-lg tracking-[0.3em]"
          autoComplete="off"
        />
      </div>

      <div className="flex gap-3">
        <Button theme="light" variant="secondary" fullWidth onClick={onBack}>
          Back
        </Button>
        <Button theme="light" fullWidth disabled={!isCorrect} onClick={onContinue}>
          Continue
        </Button>
      </div>
    </div>
  );
}