'use client';

import { useState } from 'react';
import { Coins, Info } from 'lucide-react';
import Button from '../ui/Button';

/**
 * Second verification step: confirms the user is aware of the exact
 * amount being sent by echoing back a short code.
 *
 * The verification code shown here (e.g. "56") is a PLACEHOLDER.
 * In production, this code is generated by the backend for this
 * specific transaction and returned via
 * services/verificationService.js -> startVerification(). The
 * frontend never derives it locally -- see utils/amountEncoder.js.
 *
 * @param {string} amount
 * @param {string} symbol
 * @param {string} verificationCode - placeholder, backend-issued in production
 */

export default function AmountVerification({
  amount = '5',
  symbol = 'ETH',
  verificationCode = '56',
  onContinue,
  onBack,
}) {
  const [input, setInput] = useState('');
  const isCorrect = input === verificationCode;

  return (
    <div className="vp-theme flex flex-col gap-6">
      <div>
        <div className="flex items-center gap-2 text-sm font-semibold text-[var(--vp-primary-hover)]">
          <Coins className="h-4 w-4" aria-hidden="true" />
          Amount Verification
        </div>
        <p className="mt-2 text-base text-[var(--vp-text-secondary)]">
          Confirm the code shown below to verify you recognize this amount.
        </p>
      </div>

      <div className="vp-card px-6 py-6 text-center">
        <p className="text-sm text-[var(--vp-text-secondary)]">Transaction Amount</p>
        <p className="mt-1.5 font-mono-data text-3xl font-semibold text-[var(--vp-text-primary)]">
          {amount} {symbol}
        </p>
        <div className="mt-5 border-t border-[var(--vp-border)] pt-5">
          <p className="text-sm text-[var(--vp-text-secondary)]">Generated Verification Code</p>
          <p className="mt-1.5 font-mono-data text-4xl font-bold tracking-[0.3em] text-[var(--vp-primary)]">
            {verificationCode}
          </p>
        </div>
      </div>

      <div className="flex gap-2.5 rounded-2xl border border-[var(--vp-border)] bg-[#fff9f0] px-4 py-3.5">
        <Info className="h-4 w-4 shrink-0 text-[var(--vp-secondary)] mt-0.5" aria-hidden="true" />
        <p className="text-sm leading-relaxed text-[var(--vp-text-secondary)]">
          The first digit comes from the first digit of the amount. The second digit comes from
          the number of digits in the amount.
        </p>
      </div>

      <div>
        <label htmlFor="amount-code" className="mb-1.5 block text-sm font-semibold text-[var(--vp-text-primary)]">
          Enter the code above
        </label>
        <input
          id="amount-code"
          type="text"
          inputMode="numeric"
          maxLength={verificationCode.length}
          value={input}
          onChange={(event) => setInput(event.target.value)}
          className="vp-input font-mono-data text-center text-lg tracking-[0.3em]"
          autoComplete="off"
        />
      </div>

      <div className="flex gap-3">
        <Button theme="light" variant="secondary" fullWidth onClick={onBack}>
          Back
        </Button>
        <Button theme="light" fullWidth disabled={!isCorrect} onClick={onContinue}>
          Continue
        </Button>
      </div>
    </div>
  );
}
